# List of project's own icon files
# This file is generated by update_icon_list.sh
# WARNING! All changes made in this file will be lost!

set(_PNG_FILES
)

set(_SVG_FILES
icons/breeze/actions/16/kreport-checkbox-element.svg
icons/breeze/actions/16/kreport-field-element.svg
icons/breeze/actions/16/kreport-image-element.svg
icons/breeze/actions/16/kreport-label-element.svg
icons/breeze/actions/16/kreport-line-element.svg
icons/breeze/actions/16/kreport-text-element.svg
icons/breeze/actions/22/kreport-checkbox-element.svg
icons/breeze/actions/22/kreport-field-element.svg
icons/breeze/actions/22/kreport-image-element.svg
icons/breeze/actions/22/kreport-label-element.svg
icons/breeze/actions/22/kreport-line-element.svg
icons/breeze/actions/22/kreport-text-element.svg
icons/breeze/actions/24/kreport-checkbox-element.svg
icons/breeze/actions/24/kreport-field-element.svg
icons/breeze/actions/24/kreport-image-element.svg
icons/breeze/actions/24/kreport-label-element.svg
icons/breeze/actions/24/kreport-line-element.svg
icons/breeze/actions/24/kreport-text-element.svg
)

set(_FILES ${_PNG_FILES} ${_SVG_FILES})
