set(REQUIRED_QT_VERSION "5.3.0")
find_package(Qt5 ${REQUIRED_QT_VERSION} NO_MODULE REQUIRED Core Widgets Xml PrintSupport)
find_package(KF5 5.7.0 REQUIRED CoreAddons WidgetsAddons GuiAddons Config)
find_package(KPropertyWidgets REQUIRED)
find_package(KReport REQUIRED)
set(LIB_INSTALL_DIR "lib")
include(KDECMakeSettings NO_POLICY_SCOPE)
include(KDECompilerSettings NO_POLICY_SCOPE)
if(POLICY CMP0063) # Honor visibility properties for all target types (since cmake 3.3)
    cmake_policy(SET CMP0063 NEW)
endif()
if(POLICY CMP0071) # Don't warn when combining AUTOMOC with qt5_wrap_ui() or qt5_add_resources() (since cmake 3.10)
    cmake_policy(SET CMP0071 NEW)
endif()
