#ifndef KREPORT_CONFIG_H
#define KREPORT_CONFIG_H

/* config-kreport.h. Generated by cmake from config-kreport.h.cmake */

/*! @file config-kreport.h
    Global KReport configuration (build time)
*/

//! @def KREPORT_GIT_SHA1_STRING
//! @brief Indicates the git sha1 commit which was used for compilation of KReport
#cmakedefine KREPORT_GIT_SHA1_STRING "@KREPORT_GIT_SHA1_STRING@"

//! @def KREPORT_GIT_BRANCH_STRING
//! @brief Indicates the git branch which was used for compilation of KReport
#cmakedefine KREPORT_GIT_BRANCH_STRING "@KREPORT_GIT_BRANCH_STRING@"

//! @def KREPORT_SCRIPTING
//! @brief Scripting support using JavaScript language
#cmakedefine KREPORT_SCRIPTING

//! @def KREPORT_UNFINISHED
//! @brief Defined if unfinished features of KReport are enabled
#cmakedefine KREPORT_UNFINISHED

#endif
